package com.nightjar.analysis;
import jakarta.servlet.http.*;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.*;import java.time.format.*;import java.util.*;
@RestController @RequestMapping("/api")
public class WebController {
 private final Store store=new Store(); private final String passwordHash;
 public WebController(){String hash=System.getenv().getOrDefault("NIGHTJAR_APP_PASSWORD_SHA256","").trim().toLowerCase();String plain=System.getenv().getOrDefault("NIGHTJAR_APP_PASSWORD","");passwordHash=hash.isBlank()?(plain.isBlank()?"":sha256(plain)):hash;store.loadVolume();}
 record LoginRequest(String password){} record FilterRequest(List<String>events,String fromDate,String toDate,String startTime,String endTime,boolean trimByTime,List<String>includedVariables){} record SettingsRequest(List<String>includedVariables,Map<String,String>mapping,Boolean plotDownsamplingEnabled,Integer maxPlotPoints){}
 @GetMapping("/auth") Map<String,Object>auth(HttpSession s){return Map.of("required",!passwordHash.isBlank(),"authenticated",ok(s));}
 @PostMapping("/login") ResponseEntity<?>login(@RequestBody LoginRequest r,HttpSession s){if(passwordHash.isBlank()||MessageDigest.isEqual(passwordHash.getBytes(),sha256(Objects.toString(r.password(),"")).getBytes())){s.setAttribute("nightjarAuthenticated",true);return ResponseEntity.ok(Map.of("ok",true));}return ResponseEntity.status(401).body(Map.of("error","Incorrect password"));}
 @GetMapping("/state") ResponseEntity<?>state(HttpSession s){return ok(s)?ResponseEntity.ok(store.state()):unauthorised();}
 @PostMapping(value="/upload",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<?>upload(HttpSession s,@RequestPart(value="log",required=false)MultipartFile log,@RequestPart(value="polar",required=false)MultipartFile polar,@RequestPart(value="events",required=false)MultipartFile events,@RequestPart(value="testData",required=false)MultipartFile test,@RequestPart(value="eventList",required=false)MultipartFile list,@RequestPart(value="sailChart",required=false)MultipartFile sails,@RequestPart(value="debrief",required=false)MultipartFile debrief)throws IOException{if(!ok(s))return unauthorised();store.upload(log,polar,events,test,list,sails,debrief);return ResponseEntity.ok(store.state());}
 @PostMapping("/settings") ResponseEntity<?>settings(@RequestBody SettingsRequest r,HttpSession s){if(!ok(s))return unauthorised();store.settings(r);return ResponseEntity.ok(store.state());}
 @PostMapping("/plot-data") ResponseEntity<?>plot(@RequestBody FilterRequest r,HttpSession s){return ok(s)?ResponseEntity.ok(store.filtered(r,true)):unauthorised();}
 @PostMapping("/data") ResponseEntity<?>data(@RequestBody FilterRequest r,HttpSession s){return ok(s)?ResponseEntity.ok(store.filtered(r,false)):unauthorised();}
 @PostMapping("/file-data/{source}") ResponseEntity<?>file(@PathVariable String source,@RequestBody FilterRequest r,HttpSession s){if(!ok(s))return unauthorised();return ResponseEntity.ok(Map.of("source",source,"rows",store.fileData(source,r)));}
 @PostMapping(value="/export",produces="text/csv") ResponseEntity<StreamingResponseBody>export(@RequestBody FilterRequest r,HttpSession s){if(!ok(s))return ResponseEntity.status(401).build();List<Map<String,Object>> rows=(List<Map<String,Object>>)store.filtered(r,false).get("rows");StreamingResponseBody body=out->{try(Writer w=new BufferedWriter(new OutputStreamWriter(out,StandardCharsets.UTF_8))){if(rows.isEmpty())return;List<String>h=new ArrayList<>(rows.get(0).keySet());csv(w,h);for(Map<String,Object>x:rows)csv(w,h.stream().map(k->Objects.toString(x.get(k),"")).toList());}};return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=nightjar_filtered_log_0.9.5.csv").body(body);}
 @GetMapping("/session") ResponseEntity<?>session(HttpSession s){return ok(s)?ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=nightjar_session_0.9.5.json").body(store.session()):unauthorised();}
 private boolean ok(HttpSession s){return passwordHash.isBlank()||Boolean.TRUE.equals(s.getAttribute("nightjarAuthenticated"));} private static ResponseEntity<Map<String,String>>unauthorised(){return ResponseEntity.status(401).body(Map.of("error","Sign in required"));}
 private static void csv(Writer w,List<String>v)throws IOException{for(int i=0;i<v.size();i++){if(i>0)w.write(',');w.write('"');w.write(v.get(i).replace("\"","\"\""));w.write('"');}w.write('\n');}
 private static String sha256(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 static final class Store {
  List<Map<String,Object>> rows=new ArrayList<>(),eventData=new ArrayList<>(),testData=new ArrayList<>(); List<Map<String,Object>> eventList=new ArrayList<>(),polar=new ArrayList<>(),sails=new ArrayList<>(); LinkedHashSet<String>columns=new LinkedHashSet<>(),included=new LinkedHashSet<>();Map<String,String>mapping=new LinkedHashMap<>();boolean downsample=true;int maxPoints=10000;String status="No log loaded";
  synchronized void loadVolume(){Path d=Path.of(System.getenv().getOrDefault("NIGHTJAR_DATA_DIR","/Data"));tryRead(d.resolve("logfile.csv"),"log");tryRead(d.resolve("EventData.csv"),"event");tryRead(d.resolve("TestData.csv"),"test");tryRead(d.resolve("EventList.txt"),"list");}
  void tryRead(Path p,String kind){try{if(Files.exists(p))load(Files.readAllBytes(p),kind);}catch(Exception e){status=kind+" skipped: "+e.getMessage();}}
  synchronized void upload(MultipartFile log,MultipartFile polarFile,MultipartFile event,MultipartFile test,MultipartFile list,MultipartFile sail,MultipartFile debrief)throws IOException{if(log!=null&&!log.isEmpty())load(log.getBytes(),"log");if(event!=null&&!event.isEmpty())load(event.getBytes(),"event");if(test!=null&&!test.isEmpty())load(test.getBytes(),"test");if(list!=null&&!list.isEmpty())load(list.getBytes(),"list");}
  void load(byte[]b,String kind){List<Map<String,Object>>v=parseCsv(b);switch(kind){case"log"->setRows(v);case"event"->eventData=v;case"test"->testData=v;case"list"->eventList=parseEventList(b);}}
  void setRows(List<Map<String,Object>>v){rows=v;columns.clear();v.forEach(x->columns.addAll(x.keySet()));included=new LinkedHashSet<>(columns);detect();status="Loaded "+rows.size()+" rows";}
  void detect(){mapping.clear();Map<String,List<String>>a=Map.of("timestamp",List.of("utc","time","timestamp","datetime"),"bsp",List.of("bsp","boat speed"),"twa",List.of("twa","true wind angle"),"tws",List.of("tws","true wind speed"),"vmg",List.of("vmg"),"vmg_pct",List.of("vmg%","vmg pct","vmg_pct"),"lat",List.of("lat","latitude","lat1"),"lon",List.of("lon","longitude","lon1"));a.forEach((k,n)->mapping.put(k,columns.stream().filter(c->n.contains(norm(c))).findFirst().orElse(null)));}
  synchronized Map<String,Object>state(){Map<String,Object>m=new LinkedHashMap<>();m.put("version","0.9.5");m.put("loaded",!rows.isEmpty());m.put("rowCount",rows.size());m.put("columns",columns);m.put("includedVariables",included);m.put("mapping",mapping);m.put("eventList",eventList);m.put("polar",polar);m.put("sails",sails);m.put("loadStatus",status);m.put("plotDownsamplingEnabled",downsample);m.put("maxPlotPoints",maxPoints);m.put("heapUsedMiB",(Runtime.getRuntime().totalMemory()-Runtime.getRuntime().freeMemory())/1048576);m.put("heapMaxMiB",Runtime.getRuntime().maxMemory()/1048576);m.put("eventDataRows",eventData.size());m.put("testDataRows",testData.size());return m;}
  synchronized void settings(SettingsRequest r){if(r.includedVariables()!=null)included=new LinkedHashSet<>(r.includedVariables());if(r.mapping()!=null)mapping.putAll(r.mapping());if(r.plotDownsamplingEnabled()!=null)downsample=r.plotDownsamplingEnabled();if(r.maxPlotPoints()!=null)maxPoints=Math.max(100,r.maxPlotPoints());}
  synchronized Map<String,Object>filtered(FilterRequest r,boolean plot){List<Map<String,Object>>all=filter(rows,r);int matched=all.size();List<Map<String,Object>>out=all;if(plot&&downsample&&matched>maxPoints){out=new ArrayList<>(maxPoints);double step=(matched-1d)/(maxPoints-1d);for(int i=0;i<maxPoints;i++)out.add(all.get((int)Math.round(i*step)));}List<Map<String,Object>>visible=out.stream().map(x->{Map<String,Object>y=new LinkedHashMap<>();for(String k:included)if(x.containsKey(k))y.put(k,x.get(k));return y;}).toList();Map<String,Object>m=new LinkedHashMap<>();m.put("rows",visible);m.put("warnings",List.of());m.put("sourceRows",rows.size());m.put("matchedRows",matched);m.put("returnedRows",visible.size());m.put("plotDownsamplingApplied",visible.size()<matched);m.put("mapping",mapping);return m;}
  synchronized List<Map<String,Object>>fileData(String source,FilterRequest r){return filter("test".equalsIgnoreCase(source)?testData:eventData,r).stream().limit(20000).toList();}
  List<Map<String,Object>>filter(List<Map<String,Object>>src,FilterRequest r){LocalDate from=date(r.fromDate()),to=date(r.toDate());String ts=mapping.get("timestamp");return src.stream().filter(x->{LocalDateTime d=parseTime(ts==null?findTime(x):x.get(ts));if(d==null)return from==null&&to==null;LocalDate day=d.toLocalDate();return(from==null||!day.isBefore(from))&&(to==null||!day.isAfter(to));}).toList();}
  Map<String,Object>session(){return Map.of("version","0.9.5","rowCount",rows.size(),"mapping",mapping,"includedVariables",included,"plotDownsamplingEnabled",downsample,"maxPlotPoints",maxPoints);}
  static Object findTime(Map<String,Object>x){for(var e:x.entrySet())if(List.of("utc","time","timestamp","datetime").contains(norm(e.getKey())))return e.getValue();return null;}
  static List<Map<String,Object>>parseCsv(byte[]b){String[]lines=new String(b,StandardCharsets.UTF_8).replace("\uFEFF","").split("\\R");if(lines.length==0)return List.of();List<String>h=csvLine(lines[0]).stream().map(s->s.replaceFirst("^!","")).toList();List<Map<String,Object>>out=new ArrayList<>();for(int n=1;n<lines.length;n++){if(lines[n].isBlank())continue;List<String>v=csvLine(lines[n]);Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<Math.min(h.size(),v.size());i++)m.put(h.get(i),typed(v.get(i)));out.add(m);}return out;}
  static List<Map<String,Object>>parseEventList(byte[]b){List<Map<String,Object>>out=new ArrayList<>();for(String line:new String(b,StandardCharsets.UTF_8).split("\\R")){String[]p=line.split(",",3);if(p.length==3)try{out.add(Map.of("date",LocalDate.parse(p[0].replace("\"",""),DateTimeFormatter.BASIC_ISO_DATE),"type",p[1].replace("\"",""),"event",p[2].replace("\"","")));}catch(Exception ignored){}}return out;}
  static List<String>csvLine(String s){List<String>v=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c=='"'){if(q&&i+1<s.length()&&s.charAt(i+1)=='"'){b.append('"');i++;}else q=!q;}else if(c==','&&!q){v.add(b.toString().trim());b.setLength(0);}else b.append(c);}v.add(b.toString().trim());return v;}
  static Object typed(String s){try{return Double.valueOf(s);}catch(Exception e){return s;}}static String norm(String s){return s==null?"":s.toLowerCase().replaceAll("[^a-z0-9]+"," ").trim();}static LocalDate date(String s){try{return s==null?null:LocalDate.parse(s);}catch(Exception e){return null;}}static LocalDateTime parseTime(Object o){if(o==null)return null;try{if(o instanceof Number n)return LocalDateTime.of(1899,12,30,0,0).plusSeconds(Math.round(n.doubleValue()*86400));return LocalDateTime.parse(o.toString());}catch(Exception e){return null;}}
 }
}
