package com.nightjar.analysis;
import jakarta.annotation.PostConstruct;
import org.apache.commons.csv.*;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.*;import java.time.format.*;import java.util.*;import java.util.concurrent.locks.ReentrantReadWriteLock;
@Service
public class DataStore {
 private static final int BUFFER=1024*1024; private static final long MIB=1024L*1024L,RESERVE=512L*MIB;
 private final ReentrantReadWriteLock lock=new ReentrantReadWriteLock();
 private List<Map<String,Object>> rows=new ArrayList<>(),eventData=new ArrayList<>(),testData=new ArrayList<>();
 private List<Map<String,Object>> eventList=new ArrayList<>(),polar=new ArrayList<>(),sails=new ArrayList<>();
 private LinkedHashSet<String> columns=new LinkedHashSet<>(),included=new LinkedHashSet<>(); private LinkedHashMap<String,String> mapping=new LinkedHashMap<>();
 private final List<String>warnings=new ArrayList<>(); private boolean downsample=true; private int maxPoints=10000; private String status="No log loaded";
 @PostConstruct void startup(){Path d=Path.of(System.getenv().getOrDefault("NIGHTJAR_DATA_DIR","/Data"));lock.writeLock().lock();try{loadMain(d.resolve("logfile.csv"));loadAux(d.resolve("EventData.csv"),"event");loadAux(d.resolve("TestData.csv"),"test");loadEventList(d.resolve("EventList.txt"));loadPolar(d.resolve("Polar.txt"));}finally{lock.writeLock().unlock();}}
 private void loadMain(Path p){if(!Files.exists(p))return;try(InputStream in=Files.newInputStream(p)){parseMain(in);}catch(Exception e){warn("Logfile",e);}}
 private void loadAux(Path p,String kind){if(!Files.exists(p))return;try(Reader r=reader(Files.newInputStream(p))){List<Map<String,Object>>data=parseTable(r,20000);if(kind.equals("event"))eventData=data;else testData=data;}catch(Exception e){warn(kind,e);}}
 private void loadEventList(Path p){if(!Files.exists(p))return;try(BufferedReader r=Files.newBufferedReader(p,StandardCharsets.UTF_8)){List<Map<String,Object>>out=new ArrayList<>();for(String line;(line=r.readLine())!=null;){String[]x=line.split(",",3);if(x.length==3)try{out.add(Map.of("date",LocalDate.parse(unquote(x[0]),DateTimeFormatter.BASIC_ISO_DATE),"type",unquote(x[1]),"event",unquote(x[2])));}catch(Exception ignored){}}eventList=out;}catch(Exception e){warn("Event list",e);}}
 private void loadPolar(Path p){if(!Files.exists(p))return;try(BufferedReader r=Files.newBufferedReader(p,StandardCharsets.UTF_8)){List<Map<String,Object>>out=new ArrayList<>();for(String line;(line=r.readLine())!=null;){try{double[]v=Arrays.stream(line.trim().split("[\\t,; ]+")).mapToDouble(Double::parseDouble).toArray();for(int i=1;i+1<v.length;i+=2)out.add(Map.of("tws",v[0],"twa",v[i],"targetBsp",v[i+1]));}catch(Exception ignored){}}polar=out;}catch(Exception e){warn("Polar",e);}}
 private void parseMain(InputStream input)throws IOException{List<Map<String,Object>>out=new ArrayList<>();LinkedHashSet<String>cols=new LinkedHashSet<>();long seen=0,bad=0;try(CSVParser parser=CSVFormat.DEFAULT.builder().setTrim(true).setIgnoreEmptyLines(true).get().parse(reader(input))){List<String>headers=null;for(CSVRecord rec:parser){seen++;if(headers==null){headers=new ArrayList<>();for(String v:rec){String h=strip(v);headers.add(h);cols.add(h);}continue;}if(usedHeap()>limit()){warnings.add("Memory limit reached; logfile partially loaded.");break;}Map<String,Object>row=new LinkedHashMap<>();for(int i=0;i<Math.min(headers.size(),rec.size());i++)row.put(headers.get(i),typed(rec.get(i)));Object t=findTime(row);if(t==null){bad++;continue;}out.add(row);}}
  rows=out;columns=cols;included=new LinkedHashSet<>(cols);detect();status=String.format(Locale.ROOT,"Loaded %,d rows sequentially; skipped %,d rows without time; heap %,d MiB.",out.size(),bad,usedHeap()/MIB);
 }
 private static List<Map<String,Object>>parseTable(Reader source,int max)throws IOException{List<Map<String,Object>>out=new ArrayList<>();try(CSVParser p=CSVFormat.DEFAULT.builder().setTrim(true).setIgnoreEmptyLines(true).get().parse(source)){List<String>h=null;for(CSVRecord r:p){if(h==null){h=new ArrayList<>();for(String v:r)h.add(strip(v));continue;}Map<String,Object>row=new LinkedHashMap<>();for(int i=0;i<Math.min(h.size(),r.size());i++)row.put(h.get(i),typed(r.get(i)));out.add(row);if(out.size()>=max)break;}}return out;}
 public Map<String,Object>state(){lock.readLock().lock();try{Map<String,Object>m=new LinkedHashMap<>();m.put("version",NightjarApplication.VERSION);m.put("loaded",!rows.isEmpty());m.put("rowCount",rows.size());m.put("columns",columns);m.put("includedVariables",included);m.put("mapping",mapping);m.put("eventList",eventList);m.put("polar",polar);m.put("sails",sails);m.put("loadStatus",status);m.put("loadWarnings",List.copyOf(warnings));m.put("plotDownsamplingEnabled",downsample);m.put("maxPlotPoints",maxPoints);m.put("heapUsedMiB",usedHeap()/MIB);m.put("heapMaxMiB",Runtime.getRuntime().maxMemory()/MIB);m.put("eventDataRows",eventData.size());m.put("testDataRows",testData.size());return m;}finally{lock.readLock().unlock();}}
 public void upload(MultipartFile log,MultipartFile polarFile,MultipartFile events,MultipartFile test,MultipartFile list,MultipartFile sail,MultipartFile debrief){lock.writeLock().lock();try{if(log!=null&&!log.isEmpty())try(InputStream in=log.getInputStream()){parseMain(in);}catch(Exception e){warn("Uploaded logfile",e);}if(events!=null&&!events.isEmpty())try(Reader r=reader(events.getInputStream())){eventData=parseTable(r,20000);}catch(Exception e){warn("EventData",e);}if(test!=null&&!test.isEmpty())try(Reader r=reader(test.getInputStream())){testData=parseTable(r,20000);}catch(Exception e){warn("TestData",e);}}finally{lock.writeLock().unlock();}}
 public void settings(Models.SettingsRequest r){lock.writeLock().lock();try{if(r.includedVariables()!=null)included=new LinkedHashSet<>(r.includedVariables());if(r.mapping()!=null)mapping.putAll(r.mapping());if(r.plotDownsamplingEnabled()!=null)downsample=r.plotDownsamplingEnabled();if(r.maxPlotPoints()!=null)maxPoints=Math.max(100,r.maxPlotPoints());}finally{lock.writeLock().unlock();}}
 public Models.DataResponse filtered(Models.FilterRequest r,boolean plot){lock.readLock().lock();try{List<Map<String,Object>>f=filter(rows,r),out=f;boolean sampled=plot&&downsample&&f.size()>maxPoints;if(sampled){out=new ArrayList<>(maxPoints);double step=(f.size()-1d)/(maxPoints-1d);for(int i=0;i<maxPoints;i++)out.add(f.get((int)Math.round(i*step)));}List<Map<String,Object>>visible=out.stream().map(x->{Map<String,Object>y=new LinkedHashMap<>();for(String k:included)if(x.containsKey(k))y.put(k,x.get(k));return y;}).toList();return new Models.DataResponse(visible,List.copyOf(warnings),rows.size(),f.size(),visible.size(),sampled,new LinkedHashMap<>(mapping));}finally{lock.readLock().unlock();}}
 public List<Map<String,Object>>auxiliaryData(String source,Models.FilterRequest r){lock.readLock().lock();try{return filter(source.equalsIgnoreCase("test")?testData:eventData,r).stream().limit(20000).toList();}finally{lock.readLock().unlock();}}
 private List<Map<String,Object>>filter(List<Map<String,Object>>src,Models.FilterRequest r){LocalDate from=date(r.fromDate()),to=date(r.toDate());return src.stream().filter(x->{LocalDateTime t=parseTime(findTime(x));if(t==null)return from==null&&to==null;LocalDate d=t.toLocalDate();return(from==null||!d.isBefore(from))&&(to==null||!d.isAfter(to));}).toList();}
 private void detect(){mapping.clear();aliases().forEach((k,v)->mapping.put(k,columns.stream().filter(c->v.contains(norm(c))).findFirst().orElse(null)));}
 private static Map<String,List<String>>aliases(){return Map.of("timestamp",List.of("utc","time","timestamp","datetime"),"bsp",List.of("bsp","boat speed"),"twa",List.of("twa","true wind angle"),"tws",List.of("tws","true wind speed"),"vmg",List.of("vmg"),"vmg_pct",List.of("vmg%","vmg pct","vmg_pct"),"lat",List.of("lat","latitude","lat1"),"lon",List.of("lon","longitude","lon1"));}
 private void warn(String label,Exception e){warnings.add(label+" skipped: "+Objects.toString(e.getMessage(),e.getClass().getSimpleName()));}
 private static Reader reader(InputStream in){return new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8),BUFFER);}private static long usedHeap(){Runtime r=Runtime.getRuntime();return r.totalMemory()-r.freeMemory();}private static long limit(){return Math.max(512*MIB,Runtime.getRuntime().maxMemory()-RESERVE);}private static String strip(String s){return s==null?"":s.replaceFirst("^!","").trim();}private static String norm(String s){return s==null?"":s.toLowerCase().replaceAll("[^a-z0-9%]+"," ").trim();}private static Object typed(String s){if(s==null||s.isBlank())return null;try{return Double.valueOf(s.trim());}catch(Exception e){return s.trim();}}private static Object findTime(Map<String,Object>x){for(var e:x.entrySet())if(List.of("utc","time","timestamp","datetime").contains(norm(e.getKey())))return e.getValue();return null;}private static LocalDateTime parseTime(Object o){if(o==null)return null;try{if(o instanceof Number n)return LocalDateTime.of(1899,12,30,0,0).plusSeconds(Math.round(n.doubleValue()*86400));return LocalDateTime.parse(o.toString());}catch(Exception e){return null;}}private static LocalDate date(String s){try{return s==null?null:LocalDate.parse(s);}catch(Exception e){return null;}}private static String unquote(String s){return s.trim().replaceAll("^\"|\"$","");}
}
