package com.nightjar.analysis;
import jakarta.servlet.http.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Instant;import java.util.*;
@RestController @RequestMapping("/api") public class WebController {
 private final DataStore store;private final String passwordHash;public WebController(DataStore store){this.store=store;String h=System.getenv().getOrDefault("NIGHTJAR_APP_PASSWORD_SHA256","").trim().toLowerCase();String p=System.getenv().getOrDefault("NIGHTJAR_APP_PASSWORD","");passwordHash=h.isBlank()?(p.isBlank()?"":sha256(p)):h;}
 record LoginRequest(String password){}@GetMapping("/auth")Map<String,Object>auth(HttpSession s){return Map.of("required",!passwordHash.isBlank(),"authenticated",ok(s));}@PostMapping("/login")ResponseEntity<?>login(@RequestBody LoginRequest r,HttpSession s){if(passwordHash.isBlank()||MessageDigest.isEqual(passwordHash.getBytes(),sha256(Objects.toString(r.password(),"")).getBytes())){s.setAttribute("nightjarAuthenticated",true);return ResponseEntity.ok(Map.of("ok",true));}return ResponseEntity.status(401).body(Map.of("error","Incorrect password"));}
 @GetMapping("/state")ResponseEntity<?>state(HttpSession s){return ok(s)?ResponseEntity.ok(store.state()):no();}
 @PostMapping(value="/upload",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)ResponseEntity<?>upload(HttpSession s,@RequestPart(value="log",required=false)MultipartFile log,@RequestPart(value="polar",required=false)MultipartFile polar,@RequestPart(value="events",required=false)MultipartFile events,@RequestPart(value="testData",required=false)MultipartFile test,@RequestPart(value="eventList",required=false)MultipartFile list,@RequestPart(value="sailChart",required=false)MultipartFile sail,@RequestPart(value="debrief",required=false)MultipartFile debrief){if(!ok(s))return no();store.upload(log,polar,events,test,list,sail,debrief);return ResponseEntity.ok(store.state());}
 @PostMapping("/settings")ResponseEntity<?>settings(@RequestBody Models.SettingsRequest r,HttpSession s){if(!ok(s))return no();store.settings(r);return ResponseEntity.ok(store.state());}@PostMapping("/plot-data")ResponseEntity<?>plot(@RequestBody Models.FilterRequest r,HttpSession s){return ok(s)?ResponseEntity.ok(store.filtered(r,true)):no();}@PostMapping("/data")ResponseEntity<?>data(@RequestBody Models.FilterRequest r,HttpSession s){return ok(s)?ResponseEntity.ok(store.filtered(r,false)):no();}@PostMapping("/file-data/{source}")ResponseEntity<?>file(@PathVariable String source,@RequestBody Models.FilterRequest r,HttpSession s){return ok(s)?ResponseEntity.ok(Map.of("source",source,"rows",store.auxiliaryData(source,r))):no();}
 @PostMapping(value="/export",produces="text/csv")ResponseEntity<StreamingResponseBody>export(@RequestBody Models.FilterRequest r,HttpSession s){if(!ok(s))return ResponseEntity.status(401).build();var rows=store.filtered(r,false).rows();StreamingResponseBody body=out->{try(Writer w=new BufferedWriter(new OutputStreamWriter(out,StandardCharsets.UTF_8))){if(rows.isEmpty())return;List<String>h=new ArrayList<>(rows.get(0).keySet());csv(w,h);for(var x:rows)csv(w,h.stream().map(k->Objects.toString(x.get(k),"")).toList());}};return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=nightjar_filtered_log_0.9.5.1.csv").body(body);}@GetMapping("/session")ResponseEntity<?>session(HttpSession s){return ok(s)?ResponseEntity.ok(Map.of("version",NightjarApplication.VERSION,"createdUtc",Instant.now(),"state",store.state())):no();}
 private boolean ok(HttpSession s){return passwordHash.isBlank()||Boolean.TRUE.equals(s.getAttribute("nightjarAuthenticated"));}private static ResponseEntity<Map<String,String>>no(){return ResponseEntity.status(401).body(Map.of("error","Sign in required"));}private static void csv(Writer w,List<String>v)throws IOException{for(int i=0;i<v.size();i++){if(i>0)w.write(',');w.write('"');w.write(v.get(i).replace("\"","\"\""));w.write('"');}w.write('\n');}private static String sha256(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
