spring.application.name=Nightjar Data Analysis
server.port=${PORT:8080}
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.servlet.session.timeout=8h
spring.jackson.serialization.write-dates-as-timestamps=false
server.compression.enabled=true
