package com.nightjar.analysis;
import jakarta.annotation.PostConstruct;import jakarta.servlet.http.*;import org.apache.commons.csv.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.*;import java.time.format.*;import java.time.temporal.*;import java.util.*;import java.util.concurrent.locks.ReentrantReadWriteLock;import java.util.stream.Collectors;
@RestController @RequestMapping("/api") public class WebController {
 private final Store store=new Store();private final String passwordHash;
 public WebController(){String h=System.getenv().getOrDefault("NIGHTJAR_APP_PASSWORD_SHA256","").trim().toLowerCase(Locale.ROOT),p=System.getenv().getOrDefault("NIGHTJAR_APP_PASSWORD","");passwordHash=h.isBlank()?(p.isBlank()?"":sha256(p)):h;}
 @PostConstruct void start(){store.startup();}
 record LoginRequest(String password){} record FilterRequest(List<String>events,String fromDate,String toDate,String startTime,String endTime,boolean trimByTime,List<String>includedVariables){} record SettingsRequest(List<String>includedVariables,Map<String,String>mapping,Boolean plotDownsamplingEnabled,Integer maxPlotPoints){}
 @GetMapping("/auth")Map<String,Object>auth(HttpSession s){return Map.of("required",!passwordHash.isBlank(),"authenticated",authorised(s));}
 @PostMapping("/login")ResponseEntity<?>login(@RequestBody LoginRequest r,HttpSession s){if(passwordHash.isBlank()||MessageDigest.isEqual(passwordHash.getBytes(StandardCharsets.UTF_8),sha256(Objects.toString(r.password(),"")).getBytes(StandardCharsets.UTF_8))){s.setAttribute("nightjarAuthenticated",true);return ResponseEntity.ok(Map.of("ok",true));}return ResponseEntity.status(401).body(Map.of("error","Incorrect password"));}
 @PostMapping("/logout")void logout(HttpSession s){s.invalidate();}@GetMapping("/state")ResponseEntity<?>state(HttpSession s){return authorised(s)?ResponseEntity.ok(store.state()):no();}
 @PostMapping(value="/upload",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)ResponseEntity<?>upload(HttpSession s,@RequestPart(value="log",required=false)MultipartFile log,@RequestPart(value="polar",required=false)MultipartFile polar,@RequestPart(value="events",required=false)MultipartFile events,@RequestPart(value="testData",required=false)MultipartFile test,@RequestPart(value="eventList",required=false)MultipartFile list,@RequestPart(value="sailChart",required=false)MultipartFile sail,@RequestPart(value="debrief",required=false)MultipartFile debrief){if(!authorised(s))return no();store.upload(log,polar,events,test,list,sail,debrief);return ResponseEntity.ok(store.state());}
 @PostMapping("/settings")ResponseEntity<?>settings(@RequestBody SettingsRequest r,HttpSession s){if(!authorised(s))return no();store.settings(r);return ResponseEntity.ok(store.state());}
 @PostMapping("/data")ResponseEntity<?>data(@RequestBody FilterRequest r,HttpSession s){return authorised(s)?ResponseEntity.ok(store.filtered(r,false)):no();}@PostMapping("/plot-data")ResponseEntity<?>plot(@RequestBody FilterRequest r,HttpSession s){return authorised(s)?ResponseEntity.ok(store.filtered(r,true)):no();}
 @PostMapping("/file-data/{source}")ResponseEntity<?>file(@PathVariable String source,@RequestBody FilterRequest r,HttpSession s){if(!authorised(s))return no();if(!source.equalsIgnoreCase("event")&&!source.equalsIgnoreCase("test"))return ResponseEntity.badRequest().body(Map.of("error","Source must be event or test"));return ResponseEntity.ok(Map.of("source",source,"rows",store.aux(source,r)));}
 @PostMapping(value="/export",produces="text/csv")ResponseEntity<StreamingResponseBody>export(@RequestBody FilterRequest r,HttpSession s){if(!authorised(s))return ResponseEntity.status(401).build();List<Map<String,Object>>rows=(List<Map<String,Object>>)store.filtered(r,false).get("rows");StreamingResponseBody body=out->{try(Writer w=new BufferedWriter(new OutputStreamWriter(out,StandardCharsets.UTF_8),1024*1024)){if(rows.isEmpty())return;List<String>h=new ArrayList<>(rows.get(0).keySet());csv(w,h);for(Map<String,Object>x:rows)csv(w,h.stream().map(k->Objects.toString(x.get(k),"")).toList());}};return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=nightjar_filtered_log_0.9.5.3.csv").body(body);}
 @GetMapping("/session")ResponseEntity<?>session(HttpSession s){return authorised(s)?ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=nightjar_session_0.9.5.3.json").body(Map.of("version",NightjarApplication.VERSION,"state",store.state())):no();}
 private boolean authorised(HttpSession s){return passwordHash.isBlank()||Boolean.TRUE.equals(s.getAttribute("nightjarAuthenticated"));}private static ResponseEntity<Map<String,String>>no(){return ResponseEntity.status(401).body(Map.of("error","Sign in required"));}private static String sha256(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static void csv(Writer w,List<String>v)throws IOException{for(int i=0;i<v.size();i++){if(i>0)w.write(',');w.write('"');w.write(v.get(i).replace("\"","\"\""));w.write('"');}w.write('\n');}
 static final class Store {
  static final long MIB=1048576L,RESERVE=512*MIB;static final int BUFFER=1048576;final ReentrantReadWriteLock lock=new ReentrantReadWriteLock();List<Map<String,Object>>rows=new ArrayList<>(),eventData=new ArrayList<>(),testData=new ArrayList<>(),eventList=new ArrayList<>(),polar=new ArrayList<>(),sails=new ArrayList<>();LinkedHashSet<String>columns=new LinkedHashSet<>(),included=new LinkedHashSet<>();LinkedHashMap<String,String>mapping=new LinkedHashMap<>();List<String>warnings=new ArrayList<>();boolean downsample=true;int maxPoints=10000;String status="No log loaded";
  void startup(){Path d=Path.of(System.getenv().getOrDefault("NIGHTJAR_DATA_DIR","/Data"));lock.writeLock().lock();try{loadLog(d.resolve("logfile.csv"));loadTable(d.resolve("EventData.csv"),true);loadTable(d.resolve("TestData.csv"),false);loadEvents(d.resolve("EventList.txt"));loadPolar(d.resolve("Polar.txt"));}finally{lock.writeLock().unlock();}}
  void loadLog(Path p){if(!Files.exists(p))return;try(InputStream in=Files.newInputStream(p)){parseLog(in);}catch(Exception e){warn("Logfile",e);}}
  void loadTable(Path p,boolean event){if(!Files.exists(p))return;try(Reader r=reader(Files.newInputStream(p))){if(event)eventData=parseTable(r);else testData=parseTable(r);}catch(Exception e){warn(event?"EventData":"TestData",e);}}
  void loadEvents(Path p){if(!Files.exists(p))return;try(BufferedReader r=Files.newBufferedReader(p)){List<Map<String,Object>>o=new ArrayList<>();for(String line;(line=r.readLine())!=null;){String[]x=line.split(",",3);if(x.length==3)try{o.add(Map.of("date",LocalDate.parse(unquote(x[0]),DateTimeFormatter.BASIC_ISO_DATE).toString(),"type",unquote(x[1]),"event",unquote(x[2])));}catch(Exception ignored){}}eventList=o;}catch(Exception e){warn("Event list",e);}}
  void loadPolar(Path p){if(!Files.exists(p))return;try(BufferedReader r=Files.newBufferedReader(p)){List<Map<String,Object>>o=new ArrayList<>();for(String line;(line=r.readLine())!=null;){try{double[]v=Arrays.stream(line.trim().split("[\\t,; ]+")).mapToDouble(Double::parseDouble).toArray();for(int i=1;i+1<v.length;i+=2)o.add(Map.of("tws",v[0],"twa",v[i],"targetBsp",v[i+1]));}catch(Exception ignored){}}polar=o;}catch(Exception e){warn("Polar",e);}}
  void parseLog(InputStream in)throws IOException{List<Map<String,Object>>o=new ArrayList<>();LinkedHashSet<String>c=new LinkedHashSet<>();long bad=0;try(CSVParser p=CSVFormat.DEFAULT.builder().setTrim(true).setIgnoreEmptyLines(true).get().parse(reader(in))){List<String>h=null;for(CSVRecord r:p){if(h==null){h=new ArrayList<>();for(String v:r){String n=strip(v);h.add(n);c.add(n);}continue;}if(used()>limit()){warnings.add("Memory limit reached; logfile partially loaded.");break;}Map<String,Object>x=new LinkedHashMap<>();for(int i=0;i<Math.min(h.size(),r.size());i++)x.put(h.get(i),typed(r.get(i)));if(findTime(x)==null){bad++;continue;}o.add(x);}}rows=o;columns=c;included=new LinkedHashSet<>(c);detect();status=String.format(Locale.ROOT,"Loaded %,d valid rows sequentially; skipped %,d invalid timestamps; heap %,d MiB.",o.size(),bad,used()/MIB);}
  Map<String,Object>state(){lock.readLock().lock();try{Map<String,Object>m=new LinkedHashMap<>();m.put("version",NightjarApplication.VERSION);m.put("loaded",!rows.isEmpty());m.put("rowCount",rows.size());m.put("columns",columns);m.put("includedVariables",included);m.put("mapping",mapping);m.put("eventList",eventList);m.put("polar",polar);m.put("sails",sails);m.put("loadStatus",status);m.put("loadWarnings",warnings);m.put("plotDownsamplingEnabled",downsample);m.put("maxPlotPoints",maxPoints);m.put("heapUsedMiB",used()/MIB);m.put("heapMaxMiB",Runtime.getRuntime().maxMemory()/MIB);m.put("eventDataRows",eventData.size());m.put("testDataRows",testData.size());return m;}finally{lock.readLock().unlock();}}
  void upload(MultipartFile log,MultipartFile polarF,MultipartFile events,MultipartFile test,MultipartFile list,MultipartFile sail,MultipartFile debrief){lock.writeLock().lock();try{if(log!=null&&!log.isEmpty())try(InputStream in=log.getInputStream()){parseLog(in);}catch(Exception e){warn("Uploaded logfile",e);}if(events!=null&&!events.isEmpty())try(Reader r=reader(events.getInputStream())){eventData=parseTable(r);}catch(Exception e){warn("EventData",e);}if(test!=null&&!test.isEmpty())try(Reader r=reader(test.getInputStream())){testData=parseTable(r);}catch(Exception e){warn("TestData",e);}}finally{lock.writeLock().unlock();}}
  void settings(SettingsRequest r){lock.writeLock().lock();try{if(r.includedVariables()!=null)included=r.includedVariables().stream().filter(columns::contains).collect(Collectors.toCollection(LinkedHashSet::new));if(r.mapping()!=null)r.mapping().forEach((k,v)->{if(v==null||v.isBlank()||columns.contains(v))mapping.put(k,v);});if(r.plotDownsamplingEnabled()!=null)downsample=r.plotDownsamplingEnabled();if(r.maxPlotPoints()!=null)maxPoints=Math.max(100,Math.min(2000000,r.maxPlotPoints()));}finally{lock.writeLock().unlock();}}
  Map<String,Object>filtered(FilterRequest r,boolean plot){lock.readLock().lock();try{List<Map<String,Object>>f=filter(rows,r),out=f;boolean sampled=plot&&downsample&&f.size()>maxPoints;if(sampled){out=new ArrayList<>(maxPoints);double step=(f.size()-1d)/(maxPoints-1d);for(int i=0;i<maxPoints;i++)out.add(f.get((int)Math.round(i*step)));}List<Map<String,Object>>vis=out.stream().map(x->{Map<String,Object>y=new LinkedHashMap<>();for(String k:included)if(x.containsKey(k))y.put(k,x.get(k));return y;}).toList();Map<String,Object>m=new LinkedHashMap<>();m.put("rows",vis);m.put("warnings",warnings);m.put("sourceRows",rows.size());m.put("matchedRows",f.size());m.put("returnedRows",vis.size());m.put("plotDownsamplingApplied",sampled);m.put("mapping",mapping);return m;}finally{lock.readLock().unlock();}}
  List<Map<String,Object>>aux(String source,FilterRequest r){lock.readLock().lock();try{return filter(source.equalsIgnoreCase("test")?testData:eventData,r).stream().limit(20000).toList();}finally{lock.readLock().unlock();}}
  List<Map<String,Object>>filter(List<Map<String,Object>>src,FilterRequest r){Set<String>names=r.events()==null?Set.of():new HashSet<>(r.events());Set<LocalDate>days=eventList.stream().filter(e->names.contains(e.get("event"))).map(e->LocalDate.parse(e.get("date").toString())).collect(Collectors.toSet());LocalDate from=date(r.fromDate()),to=date(r.toDate());LocalTime st=time(r.startTime(),LocalTime.MIN),en=time(r.endTime(),LocalTime.MAX.withNano(0));return src.stream().filter(x->{LocalDateTime z=parseDateTime(findTime(x));if(z==null)return days.isEmpty()&&from==null&&to==null;LocalDate d=z.toLocalDate();if(!days.isEmpty()&&!days.contains(d))return false;if(days.isEmpty()&&((from!=null&&d.isBefore(from))||(to!=null&&d.isAfter(to))))return false;return!r.trimByTime()||(!z.toLocalTime().isBefore(st)&&!z.toLocalTime().isAfter(en));}).toList();}
  void detect(){mapping.clear();aliases().forEach((k,v)->mapping.put(k,columns.stream().filter(c->v.contains(norm(c))).findFirst().orElse(null)));}
  static Map<String,List<String>>aliases(){return Map.ofEntries(Map.entry("timestamp",List.of("utc","time","timestamp","datetime")),Map.entry("bsp",List.of("bsp","boat speed","log bsp")),Map.entry("twa",List.of("twa","true wind angle")),Map.entry("tws",List.of("tws","true wind speed")),Map.entry("awa",List.of("awa","apparent wind angle")),Map.entry("aws",List.of("aws")),Map.entry("vmg",List.of("vmg","velocity made good")),Map.entry("vmg_pct",List.of("vmg%","vmg pct","vmg_pct")),Map.entry("heel",List.of("heel")),Map.entry("drift",List.of("drift","tide rate")),Map.entry("lat",List.of("lat","latitude","lat1")),Map.entry("lon",List.of("lon","longitude","lon1")),Map.entry("sog",List.of("sog")),Map.entry("cog",List.of("cog")),Map.entry("sail",List.of("sail","foresail_id","foresail")));}
  static List<Map<String,Object>>parseTable(Reader r)throws IOException{List<Map<String,Object>>o=new ArrayList<>();try(CSVParser p=CSVFormat.DEFAULT.builder().setTrim(true).setIgnoreEmptyLines(true).get().parse(r)){List<String>h=null;for(CSVRecord q:p){if(h==null){h=new ArrayList<>();for(String v:q)h.add(strip(v));continue;}Map<String,Object>x=new LinkedHashMap<>();for(int i=0;i<Math.min(h.size(),q.size());i++)x.put(h.get(i),typed(q.get(i)));o.add(x);}}return o;}
  void warn(String n,Exception e){warnings.add(n+" skipped: "+Objects.toString(e.getMessage(),e.getClass().getSimpleName()));}static Reader reader(InputStream in){return new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8),BUFFER);}static long used(){Runtime r=Runtime.getRuntime();return r.totalMemory()-r.freeMemory();}static long limit(){return Math.max(512*MIB,Runtime.getRuntime().maxMemory()-RESERVE);}static String strip(String s){return s==null?"":s.replaceFirst("^!","").trim();}static String norm(String s){return s==null?"":s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9%]+"," ").trim();}static Object typed(String s){if(s==null||s.isBlank())return null;try{return Double.valueOf(s.trim());}catch(Exception e){return s.trim();}}static Object findTime(Map<String,Object>x){for(var e:x.entrySet())if(List.of("utc","time","timestamp","datetime","date time").contains(norm(e.getKey())))return e.getValue();return null;}static LocalDateTime parseDateTime(Object input){if(input==null)return null;if(input instanceof Number n)return LocalDateTime.of(1899,12,30,0,0).plusSeconds(Math.round(n.doubleValue()*86400));String s=input.toString().trim();try{double n=Double.parseDouble(s);return LocalDateTime.of(1899,12,30,0,0).plusSeconds(Math.round(n*86400));}catch(Exception ignored){}for(DateTimeFormatter f:List.of(DateTimeFormatter.ISO_LOCAL_DATE_TIME,DateTimeFormatter.ofPattern("d/M/uuuu H:mm[:ss]"),DateTimeFormatter.ofPattern("d-M-uuuu H:mm[:ss]")))try{return LocalDateTime.parse(s,f);}catch(Exception ignored){}return null;}static LocalDate date(String s){try{return s==null||s.isBlank()?null:LocalDate.parse(s);}catch(Exception e){return null;}}static LocalTime time(String s,LocalTime f){try{return s==null||s.isBlank()?f:LocalTime.parse(s);}catch(Exception e){return f;}}static String unquote(String s){return s.trim().replaceAll("^\"|\"$","");}
 }
}
